export const dashboardData = {
  // Fleet Management KPIs
  kpis: {
    todaysFuel: { value: "1,247", unit: "L", change: "+5.2%" },
    activeTrips: { value: "23", unit: "", change: "+12%" },
    theftAlerts: { value: "3", unit: "Critical", change: "-2 from yesterday" },
    fleetEfficiency: { value: "2.85", unit: "KM/L", change: "+0.15" }
  },

  // 7-day fuel consumption data
  fuelConsumption: [
    { day: "Mon", consumption: 1150, target: 1200 },
    { day: "Tue", consumption: 1200, target: 1200 },
    { day: "Wed", consumption: 1180, target: 1200 },
    { day: "Thu", consumption: 1250, target: 1200 },
    { day: "Fri", consumption: 1220, target: 1200 },
    { day: "Sat", consumption: 1100, target: 1200 },
    { day: "Sun", consumption: 1247, target: 1200 }
  ],

  // Vehicle efficiency comparison
  vehicleEfficiency: [
    { vehicle: "TRK-001", efficiency: 3.2, target: 3.0 },
    { vehicle: "TRK-002", efficiency: 2.8, target: 3.0 },
    { vehicle: "TRK-003", efficiency: 3.1, target: 3.0 },
    { vehicle: "TRK-004", efficiency: 2.5, target: 3.0 },
    { vehicle: "TRK-005", efficiency: 2.9, target: 3.0 }
  ],

  // Recent Activities
  recentActivities: [
    {
      id: "ACT-001",
      time: "10:30 AM",
      tripId: "TRP-2401",
      vehicle: "TRK-001",
      fuel: "45.2L",
      variance: "+2.1L",
      status: "normal",
      timestamp: new Date(2025, 9, 11, 10, 30)
    },
    {
      id: "ACT-002", 
      time: "10:15 AM",
      tripId: "TRP-2402",
      vehicle: "TRK-003",
      fuel: "38.7L",
      variance: "-1.5L",
      status: "efficient",
      timestamp: new Date(2025, 9, 11, 10, 15)
    },
    {
      id: "ACT-003",
      time: "09:45 AM", 
      tripId: "TRP-2403",
      vehicle: "TRK-005",
      fuel: "52.8L",
      variance: "+8.2L",
      status: "alert",
      timestamp: new Date(2025, 9, 11, 9, 45)
    },
    {
      id: "ACT-004",
      time: "09:30 AM",
      tripId: "TRP-2404", 
      vehicle: "TRK-002",
      fuel: "41.3L",
      variance: "+0.8L",
      status: "normal",
      timestamp: new Date(2025, 9, 11, 9, 30)
    },
    {
      id: "ACT-005",
      time: "09:00 AM",
      tripId: "TRP-2405",
      vehicle: "TRK-004", 
      fuel: "47.1L",
      variance: "+3.4L",
      status: "normal",
      timestamp: new Date(2025, 9, 11, 9, 0)
    }
  ],

  orders: [
    // Legacy order data for backward compatibility
    {
      id: "ORD-1001",
      partyName: "Acme Corporation",
      media: { type: "Vinyl", icon: "🎨" },
      sqFt: 120,
      paymentStatus: "paid",
      orderStatus: "completed",
      date: new Date(2025, 0, 15),
      amount: 8500,
      orderType: "local",
    },
    {
      id: "ORD-1002",
      partyName: "Globex Inc",
      media: { type: "Fabric", icon: "🧶" },
      sqFt: 80,
      paymentStatus: "cod",
      orderStatus: "pending",
      date: new Date(2025, 0, 20),
      amount: 5600,
      orderType: "courier",
    },

    // February 2025 - 3 orders
    {
      id: "ORD-1003",
      partyName: "Initech LLC",
      media: { type: "Canvas", icon: "🖼️" },
      sqFt: 180,
      paymentStatus: "unpaid",
      orderStatus: "urgent",
      date: new Date(2025, 1, 10),
      amount: 12000,
      orderType: "local",
    },
    {
      id: "ORD-1004",
      partyName: "Umbrella Corp",
      media: { type: "Paper", icon: "📄" },
      sqFt: 65,
      paymentStatus: "monthly",
      orderStatus: "completed",
      date: new Date(2025, 1, 25),
      amount: 3200,
      orderType: "replacement",
    },
    {
      id: "ORD-1005",
      partyName: "Wayne Enterprises",
      media: { type: "Silk", icon: "👔" },
      sqFt: 150,
      paymentStatus: "paid",
      orderStatus: "completed",
      date: new Date(2025, 1, 28),
      amount: 11250,
      orderType: "courier",
    },

    // March 2025 - 1 order
    {
      id: "ORD-1006",
      partyName: "Stark Industries",
      media: { type: "Vinyl", icon: "🎨" },
      sqFt: 200,
      paymentStatus: "unpaid",
      orderStatus: "pending",
      date: new Date(2025, 2, 5),
      amount: 15000,
      orderType: "local",
    },

    // April 2025 - 2 orders
    {
      id: "ORD-1007",
      partyName: "Oscorp Inc",
      media: { type: "Fabric", icon: "🧶" },
      sqFt: 90,
      paymentStatus: "paid",
      orderStatus: "completed",
      date: new Date(2025, 3, 12),
      amount: 6750,
      orderType: "foc",
    },
    {
      id: "ORD-1008",
      partyName: "Cyberdyne Systems",
      media: { type: "Canvas", icon: "🖼️" },
      sqFt: 110,
      paymentStatus: "monthly",
      orderStatus: "pending",
      date: new Date(2025, 3, 20),
      amount: 8250,
      orderType: "courier",
    },

    // May 2025 - 2 orders
    {
      id: "ORD-1009",
      partyName: "Wonka Industries",
      media: { type: "Paper", icon: "📄" },
      sqFt: 75,
      paymentStatus: "cod",
      orderStatus: "urgent",
      date: new Date(2025, 4, 1),
      amount: 4500,
      orderType: "local",
    },
    {
      id: "ORD-1010",
      partyName: "Monsters Inc",
      media: { type: "Silk", icon: "👔" },
      sqFt: 130,
      paymentStatus: "paid",
      orderStatus: "completed",
      date: new Date(2025, 4, 15),
      amount: 9750,
      orderType: "replacement",
    },

    // June 2025 - 2 orders
    {
      id: "ORD-1011",
      partyName: "Pied Piper",
      media: { type: "Vinyl", icon: "🎨" },
      sqFt: 95,
      paymentStatus: "paid",
      orderStatus: "completed",
      date: new Date(2025, 5, 10),
      amount: 7125,
      orderType: "local",
    },
    {
      id: "ORD-1012",
      partyName: "Hooli",
      media: { type: "Fabric", icon: "🧶" },
      sqFt: 110,
      paymentStatus: "unpaid",
      orderStatus: "pending",
      date: new Date(2025, 5, 20),
      amount: 7700,
      orderType: "courier",
    },

    // July 2025 - 2 orders
    {
      id: "ORD-1013",
      partyName: "Dunder Mifflin",
      media: { type: "Paper", icon: "📄" },
      sqFt: 85,
      paymentStatus: "paid",
      orderStatus: "completed",
      date: new Date(2025, 6, 5),
      amount: 5100,
      orderType: "local",
    },
    {
      id: "ORD-1014",
      partyName: "Bluth Company",
      media: { type: "Canvas", icon: "🖼️" },
      sqFt: 150,
      paymentStatus: "monthly",
      orderStatus: "completed",
      date: new Date(2025, 6, 15),
      amount: 11250,
      orderType: "courier",
    },

    // August 2025 - 2 orders
    {
      id: "ORD-1015",
      partyName: "Sterling Cooper",
      media: { type: "Silk", icon: "👔" },
      sqFt: 125,
      paymentStatus: "paid",
      orderStatus: "completed",
      date: new Date(2025, 7, 1),
      amount: 9375,
      orderType: "local",
    },
    {
      id: "ORD-1016",
      partyName: "Veridian Dynamics",
      media: { type: "Vinyl", icon: "🎨" },
      sqFt: 180,
      paymentStatus: "unpaid",
      orderStatus: "pending",
      date: new Date(2025, 7, 8),
      amount: 13500,
      orderType: "courier",
    },
  ],
  activities: [
    {
      id: 1,
      user: "Sophia Clark",
      action: "updated order",
      orderId: "#ORD-1016",
      details: "Vinyl, 180 sq. ft",
      time: "2 hours ago",
      icon: "RefreshCcw",
      iconColor: "text-blue-500",
      iconBg: "bg-blue-100",
    },
    {
      id: 2,
      user: "Liam Carter",
      action: "order shipped",
      orderId: "#ORD-1015",
      details: "Courier: Delhivery",
      time: "3 hours ago",
      icon: "Package",
      iconColor: "text-purple-500",
      iconBg: "bg-purple-100",
    },
    {
      id: 3,
      user: "Noah Bennett",
      action: "payment received",
      orderId: "#ORD-1014",
      details: "₹11,250",
      time: "5 hours ago",
      icon: "DollarSign",
      iconColor: "text-green-500",
      iconBg: "bg-green-100",
    },
    {
      id: 4,
      user: "Emma Wilson",
      action: "created new order",
      orderId: "#ORD-1013",
      details: "Paper, 85 sq. ft",
      time: "1 day ago",
      icon: "FilePlus",
      iconColor: "text-orange-500",
      iconBg: "bg-orange-100",
    },
    {
      id: 5,
      user: "Oliver Taylor",
      action: "updated payment status",
      orderId: "#ORD-1012",
      details: "Unpaid → Pending",
      time: "1 day ago",
      icon: "CreditCard",
      iconColor: "text-red-500",
      iconBg: "bg-red-100",
    },
    {
      id: 6,
      user: "Ava Martinez",
      action: "completed order",
      orderId: "#ORD-1011",
      details: "Vinyl, 95 sq. ft",
      time: "2 days ago",
      icon: "CheckCircle",
      iconColor: "text-green-500",
      iconBg: "bg-green-100",
    },
    {
      id: 7,
      user: "William Johnson",
      action: "requested revision",
      orderId: "#ORD-1010",
      details: "Silk, 130 sq. ft",
      time: "3 days ago",
      icon: "Edit",
      iconColor: "text-yellow-500",
      iconBg: "bg-yellow-100",
    },
  ],    
};
